import pathlib as P
L=P.Path('src/scenes/V0StartMenuScene.js')
s=[]
s.append('/**')
s.append(' * V0StartMenuScene.js - Animated start screen from v0 design.')
s.append(' */')
s.append('import Scene from "./Scene.js";')
s.append('const MOTES_COUNT = 26;')
s.append('export class V0StartMenuScene extends Scene {')
s.append('  constructor(sm,eb,um,sl) { super(sm,eb,um,sl); this._b=this._k.bind(this); }')
s.append('  async enter(p={}) { this.p=p; this._b(); this._m(); this._a(); }')
s.append('  _b() {')
s.append('    const m=document.createElement("div");')
s.append('    m.className="v0-start-main";')
s.append('    m.style.cssText="position:relative;width:100%;height:100dvh;overflow:hidden;background:#000;cursor:pointer;user-select:none;-webkit-user-select:none;";')
s.append('    m.setAttribute("role","button");m.setAttribute("tabindex","0");m.setAttribute("aria-label","Press to start");')
s.append('    const a=document.createElement("div");a.className="anim-ambient";a.style.cssText="position:absolute;inset:0;animation:ambientlight 9s ease-in-out infinite;";')
s.append('    const k=document.createElement("div");k.className="anim-kenburns";k.style.cssText="position:absolute;inset:0;background-size:cover;background-position:center;background-image:url(\'assets/images/backgrounds/classroom-hero.jpg\');animation:kenburns 26s ease-in-out infinite;";a.appendChild(k);m.appendChild(a);')
s.append('    const r=document.createElement("div");r.className="anim-rays";r.setAttribute("aria-hidden","true");r.style.cssText="position:absolute;inset:-25%;animation:raysdrift 14s ease-in-out infinite;background:repeating-linear-gradient(100deg,rgba(255,230,170,0.14) 0px,rgba(255,230,170,0.14) 2px,transparent 2px,transparent 26px);mix-blend-mode:screen;mask-image:radial-gradient(120% 90% at 15% 10%,black 0%,transparent 65%);-webkit-mask-image:radial-gradient(120% 90% at 15% 10%,black 0%,transparent 65%);pointer-events:none;";m.appendChild(r);')
s.append('    const mo=document.createElement("div");mo.id="v0-motes-container";mo.setAttribute("aria-hidden","true");mo.style.cssText="pointer-events:none;position:absolute;inset:0;overflow:hidden;";m.appendChild(mo);')
s.append('    const f=document.createElement("div");f.className="anim-flicker";f.setAttribute("aria-hidden","true");f.style.cssText="position:absolute;inset:0;background:rgba(0,255,255,0.05);animation:flicker 6s steps(1) infinite;mix-blend-mode:overlay;pointer-events:none;";m.appendChild(f);')
s.append('    const v=document.createElement("div");v.setAttribute("aria-hidden","true");v.style.cssText="position:absolute;inset:0;background:radial-gradient(120% 90% at 50% 35%,transparent 45%,rgba(0,0,0,0.55) 100%),linear-gradient(to top,rgba(0,0,0,0.85) 0%,rgba(0,0,0,0.15) 35%,transparent 60%);pointer-events:none;";m.appendChild(v);')
s.append('    const t=document.createElement("div");t.setAttribute("aria-hidden","true");t.style.cssText="position:absolute;inset-x:0;top:0;height:6vh;background:#000;";m.appendChild(t);')
s.append('    const b=document.createElement("div");b.setAttribute("aria-hidden","true");b.style.cssText="position:absolute;inset-x:0;bottom:0;height:6vh;background:#000;";m.appendChild(b);')
s.append('    const u=document.createElement("div");u.style.cssText="position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:flex-end;padding-bottom:16vh;";')
s.append('    const tb=document.createElement("div");tb.style.cssText="animation:fadeup 1.2s ease-out both;animation-delay:0.2s;text-align:center;";')
s.append('    const sp=document.createElement("p");sp.style.cssText="margin-bottom:12px;font-size:12px;letter-spacing:0.5em;text-transform:uppercase;color:rgba(170,230,255,0.7);";sp.textContent="A Visual Novel";tb.appendChild(sp);')
s.append('    const ti=document.createElement("h1");ti.className="anim-titleglow";ti.style.cssText="font-family:Georgia,serif;font-size:clamp(2rem,7vw,5rem);font-weight:700;letter-spacing:0.15em;color:#fff;margin:0;animation:titleglow 4s ease-in-out infinite;text-shadow:0 0 12px rgba(120,190,255,0.35),0 0 30px rgba(90,150,255,0.25),0 2px 6px rgba(0,0,0,0.6);";ti.textContent="After Class";tb.appendChild(ti);u.appendChild(tb);')
s.append('    const bt=document.createElement("button");bt.type="button";bt.id="v0-press-start-btn";bt.className="anim-press";bt.style.cssText="margin-top:40px;cursor:pointer;font-size:clamp(12px,2vw,16px);font-weight:500;letter-spacing:0.4em;text-transform:uppercase;color:rgba(255,255,255,0.9);background:none;border:none;outline:none;padding:8px 24px;animation:presspulse 1.6s ease-in-out infinite;animation-delay:1s;";bt.textContent="Press Start";u.appendChild(bt);')
s.append('    const h=document.createElement("p");h.style.cssText="margin-top:16px;font-size:10px;letter-spacing:0.3em;text-transform:uppercase;color:rgba(255,255,255,0.4);";h.textContent="Click anywhere \u00b7 Enter \u00b7 Space";u.appendChild(h);')
s.append('    m.appendChild(u);')
s.append('    this._f=document.createElement("div");this._f.style.cssText="position:absolute;inset:0;z-index:10;display:none;align-items:center;justify-content:center;background:rgba(0,0,0,0.7);backdrop-filter:blur(8px);animation:fadeup 0.4s ease-out both;";')
s.append('    const ft=document.createElement("p");ft.style.cssText="font-family:Georgia,serif;font-size:clamp(1.5rem,4vw,2.5rem);letter-spacing:0.1em;color:#fff;";ft.textContent="Loading...";this._f.appendChild(ft);m.appendChild(this._f);')
s.append('    while(this.sceneLayer.firstChild)this.sceneLayer.removeChild(this.sceneLayer.firstChild);this.sceneLayer.appendChild(m);this._el=m;')
s.append('  }')
L.write_text('\n'.join(s), encoding='utf-8')
print('Part 1 done')
